### PR TITLE
Feature/issue 37 rbac permissions scope authorization

### LINKED ISSUE #37: feat: implement RBAC permissions and scope authorization
## Summary

Implement backend authorization using role-based access control, permission checks, and operational scope validation.

This issue establishes the authorization foundation required before organization, customer, ticket, dashboard, report, audit, and lookup APIs are implemented.

## Scope

- Add backend permission authorization policies.
- Add role-based authorization checks.
- Add scope-based authorization services.
- Add current user context abstraction.
- Add resource access validation helpers.
- Add query filtering helpers for scoped reads.
- Add write authorization helpers for scoped actions.
- Add permission constants or strongly typed permission definitions.
- Add role constants or strongly typed role definitions.
- Add scope type model support:
  - Region
  - Country
  - Account
  - Campaign
- Add authorization failure handling.
- Add safe structured logs for authorization denials.
- Add frontend role-aware navigation based on authenticated user data.
- Add tests for role, permission, and scope behavior.

## Backend Scope

- Permission policy registration.
- Role policy registration.
- Scope authorization service.
- Current user service.
- Access decision helpers.
- Scoped query helpers.
- Resource ownership/scope validation patterns.
- Authorization denial result handling.

## Frontend Scope

- Role-aware navigation.
- Permission-aware UI visibility where simple.
- Hide unauthorized actions for better UX.
- Do not treat frontend visibility as a security boundary.

## Database Scope

- Use existing Roles, Permissions, UserRoles, RolePermissions, and UserScopes.
- Add indexes only if missing and required for role/permission/scope queries.
- No new business tables unless required by current schema gaps.

## Acceptance Criteria

- Backend authorization is the source of truth.
- Users must be authenticated before accessing protected resources.
- Users must have required role/permission before executing protected actions.
- Users must operate only within assigned operational scope.
- Viewer write actions are denied.
- Agent admin actions are denied.
- Cross-scope access is denied.
- Scoped list filtering returns only authorized data.
- Authorization denials return safe API responses.
- Authorization denials are logged without exposing sensitive data.
- Frontend navigation reflects user roles/permissions as UX only.
- Tests prove role, permission, and scope rules.

## Required Test Scenarios

- Viewer cannot execute write action.
- Agent cannot access admin-only action.
- Supervisor cannot access records outside assigned account/campaign.
- Manager can read data only within assigned region.
- User without required permission is denied.
- User without required scope is denied.
- Scoped list returns only records inside assigned scope.
- Frontend hidden actions are backed by backend authorization tests.

## Out of Scope

- Business CRUD APIs.
- User management implementation.
- Organization management implementation.
- Customer management implementation.
- Ticket workflows.
- Dashboard implementation.
- Audit views.
- Treating Angular visibility as security.
- Advanced policy administration UI.

## Validation

- [ ] dotnet restore
- [ ] dotnet build
- [ ] dotnet test
- [ ] npm install or npm ci
- [ ] npm run build
- [ ] npm run test, if configured
- [ ] Confirm Viewer write denial.
- [ ] Confirm Agent admin denial.
- [ ] Confirm cross-scope denial.
- [ ] Confirm scoped list filtering.
- [ ] Confirm backend authorization works independently from frontend visibility.
- [ ] Confirm authorization logs do not expose sensitive data.

### PR DESCRIPTION
**Pull request by froblerom**
## Summary

Implements the RBAC, permission, and operational scope authorization foundation for OpsSphere.

This PR adds backend authorization infrastructure based on roles, permissions, and operational scopes. It introduces typed authorization constants, current-user authorization abstractions, DB-backed permission checks, hierarchy-aware scope validation, scoped query helpers, authorization smoke endpoints, safe authorization denial logging, and frontend role/permission-aware navigation as UX only.

## Added / Changed

- Added typed authorization constants for:
  - Runtime roles
  - Permission codes
  - Scope types
- Added current-user authorization abstractions for:
  - Current authenticated user context
  - Current user authorization profile
  - Permission checks
  - Scope checks
- Added DB-backed permission authorization handling.
- Registered one ASP.NET Core authorization policy per permission code.
- Added hierarchy-aware scope authorization for:
  - Region
  - Country
  - Account
  - Campaign
- Added scoped query filtering helpers for authorized reads.
- Added structured authorization decision support with safe reason codes.
- Added authorization smoke endpoints to validate role, permission, and scope behavior.
- Added safe structured logging for authorization denials.
- Updated frontend auth support with:
  - Role constants
  - Permission constants
  - `hasRole`
  - `hasPermission`
  - `hasAnyPermission`
  - Role/permission-aware navigation visibility
- Added frontend comments clarifying that UI visibility is UX only and backend authorization is the source of truth.
- Added backend integration tests for role, permission, and scope behavior.
- Added frontend tests for role/permission helper behavior and navigation visibility.
- Updated `tsconfig.json` with explicit `rootDir` to satisfy the TypeScript compiler output layout requirement.

## Validation

- [x] Reviewed changed files.
- [x] Confirmed scope matches the related issue.
- [x] Confirmed validation expectations from `docs/implementation-guardrails.md` were met or documented.
- [x] Ran `dotnet build`.
- [x] Ran `dotnet test`.
- [x] Ran `npm run build`.
- [x] Ran `npm run test`.
- [x] Ran `dotnet ef database update --project src/OpsSphere.Infrastructure --startup-project src/OpsSphere.Api`.
- [x] Confirmed database was already up to date.
- [x] Ran the API locally through `dotnet run --project src/OpsSphere.Api`.
- [x] Confirmed Admin authorization smoke endpoint succeeds with a valid JWT.
- [x] Confirmed protected authorization smoke endpoint rejects requests without a token.
- [x] Confirmed Viewer write denial through tests.
- [x] Confirmed Agent admin denial through tests.
- [x] Confirmed Supervisor cross-scope denial through tests.
- [x] Confirmed scoped list filtering through tests.
- [x] Confirmed backend authorization works independently from frontend visibility.
- [x] Confirmed authorization denial logging does not expose sensitive data.

## Scope Confirmation

- [x] This PR contains no out-of-scope work.
- [x] This PR does not introduce unrelated source, package, migration, Docker, or GitHub Actions changes.
- [x] This PR does not implement business CRUD APIs.
- [x] This PR does not implement user, organization, customer, ticket, dashboard, report, or audit management workflows.
- [x] This PR does not treat Angular visibility as a security boundary.

## Related Issue

Closes #37

## Checklist

- [x] Branch name includes the issue number.
- [x] Related issue defines scope, out of scope, acceptance criteria, and validation.
- [x] Architecture boundaries and MVP limits from `docs/implementation-guardrails.md` are respected.
- [x] Documentation is updated when behavior, architecture, setup, or validation expectations change.

### CODE REVIEW

**Review by froblerom — COMMENTED** [review]
It's great.
